# This workflow is triggered when someone create a new release in GitHub
name: Trigger Release creation

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: self-hosted

    # The cimg-mvn-cache is an image containing a .m2 folder warmed-up
    # with common Jahia dependencies. Using this prevents maven from
    # downloading the entire world when building.
    # More on https://github.com/Jahia/cimg-mvn-cache
    container:
      image: jahia/cimg-mvn-cache:ga_cimg_openjdk_8.0.312-node
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Gradle
        run: ./gradlew clean test jar

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifacts
          path: |
            ./build/libs/*.jar
          retention-days: 2
          if-no-files-found: error

      - name: Publish to Maven Central
        run: ./gradlew publish
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
